/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage.pk;

import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author feran
 */
public class AcademicMDashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public AcademicMDashboard() {
        initComponents();
   
        fullNameW.setText(LoginSesion.fullUserName);
        panelSemester.setVisible(false);
        panelSC.setVisible(false);
        PanelLC.setVisible(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fullNameW = new javax.swing.JLabel();
        lCBtn = new javax.swing.JButton();
        semesterBtn = new javax.swing.JButton();
        sCBtn = new javax.swing.JButton();
        panelCenter = new javax.swing.JPanel();
        panelSemester = new javax.swing.JPanel();
        showUsersBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        semesterIdField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        descriptionField = new javax.swing.JTextField();
        findBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        createBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBD = new javax.swing.JTable();
        SectionField = new javax.swing.JTextField();
        panelSC = new javax.swing.JPanel();
        showUsersBtn1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        createBtn1 = new javax.swing.JButton();
        updateBtn1 = new javax.swing.JButton();
        deleteBtn1 = new javax.swing.JButton();
        clearBtn1 = new javax.swing.JButton();
        exitBtn1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableSC = new javax.swing.JTable();
        sCComboSId = new javax.swing.JComboBox();
        sCComboCId = new javax.swing.JComboBox();
        sCComboSemId = new javax.swing.JComboBox();
        PanelLC = new javax.swing.JPanel();
        showUsersBtn2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        createBtn2 = new javax.swing.JButton();
        updateBtn2 = new javax.swing.JButton();
        deleteBtn2 = new javax.swing.JButton();
        clearBtn2 = new javax.swing.JButton();
        exitBtn2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableBD2 = new javax.swing.JTable();
        lCComboLId = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        lCComboCId = new javax.swing.JComboBox();
        lCComboSId = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(220, 122, 55));

        fullNameW.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        fullNameW.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(fullNameW, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(fullNameW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lCBtn.setBackground(new java.awt.Color(255, 102, 255));
        lCBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lCBtn.setText("Lecturer/Course");
        lCBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lCBtnActionPerformed(evt);
            }
        });

        semesterBtn.setBackground(new java.awt.Color(102, 153, 255));
        semesterBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        semesterBtn.setText("Semester");
        semesterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semesterBtnActionPerformed(evt);
            }
        });

        sCBtn.setBackground(new java.awt.Color(153, 102, 255));
        sCBtn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        sCBtn.setText("Student/Course");
        sCBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sCBtnActionPerformed(evt);
            }
        });

        panelCenter.setBackground(new java.awt.Color(204, 204, 255));

        panelSemester.setBackground(new java.awt.Color(204, 204, 255));

        showUsersBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        showUsersBtn.setText("Show Semesters");
        showUsersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showUsersBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Semester ID");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Description");

        findBtn.setText("Find");
        findBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findBtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Section");

        createBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        createBtn.setText("Create");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        updateBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        clearBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(255, 102, 102));
        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        tableBD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableBD);

        javax.swing.GroupLayout panelSemesterLayout = new javax.swing.GroupLayout(panelSemester);
        panelSemester.setLayout(panelSemesterLayout);
        panelSemesterLayout.setHorizontalGroup(
            panelSemesterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSemesterLayout.createSequentialGroup()
                .addGroup(panelSemesterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSemesterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelSemesterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(22, 22, 22)
                        .addGroup(panelSemesterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(descriptionField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(semesterIdField, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(SectionField, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(findBtn))
                    .addGroup(panelSemesterLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(showUsersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelSemesterLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(createBtn)
                .addGap(51, 51, 51)
                .addComponent(updateBtn)
                .addGap(50, 50, 50)
                .addComponent(deleteBtn)
                .addGap(42, 42, 42)
                .addComponent(clearBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        panelSemesterLayout.setVerticalGroup(
            panelSemesterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSemesterLayout.createSequentialGroup()
                .addGroup(panelSemesterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSemesterLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(showUsersBtn)
                        .addGap(47, 47, 47)
                        .addGroup(panelSemesterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(semesterIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(findBtn))
                        .addGap(18, 18, 18)
                        .addGroup(panelSemesterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(descriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelSemesterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(SectionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 36, Short.MAX_VALUE))
                    .addGroup(panelSemesterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)))
                .addGap(69, 69, 69)
                .addGroup(panelSemesterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createBtn)
                    .addComponent(updateBtn)
                    .addComponent(deleteBtn)
                    .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearBtn))
                .addGap(23, 23, 23))
        );

        panelSC.setBackground(new java.awt.Color(222, 189, 255));

        showUsersBtn1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        showUsersBtn1.setText("Show Student Relation");
        showUsersBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showUsersBtn1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Student ID");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Course ID");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Semester ID");

        createBtn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        createBtn1.setText("Create");
        createBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtn1ActionPerformed(evt);
            }
        });

        updateBtn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        updateBtn1.setText("Update");
        updateBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtn1ActionPerformed(evt);
            }
        });

        deleteBtn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deleteBtn1.setText("Delete");
        deleteBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtn1ActionPerformed(evt);
            }
        });

        clearBtn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        clearBtn1.setText("Clear");
        clearBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtn1ActionPerformed(evt);
            }
        });

        exitBtn1.setBackground(new java.awt.Color(255, 102, 102));
        exitBtn1.setText("Exit");
        exitBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtn1ActionPerformed(evt);
            }
        });

        tableSC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableSC);

        sCComboSId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sCComboSIdItemStateChanged(evt);
            }
        });
        sCComboSId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sCComboSIdActionPerformed(evt);
            }
        });

        sCComboCId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sCComboCIdItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panelSCLayout = new javax.swing.GroupLayout(panelSC);
        panelSC.setLayout(panelSCLayout);
        panelSCLayout.setHorizontalGroup(
            panelSCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelSCLayout.createSequentialGroup()
                        .addGroup(panelSCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(22, 22, 22)
                        .addGroup(panelSCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sCComboSId, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sCComboCId, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sCComboSemId, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(showUsersBtn1))
                .addGap(93, 93, 93)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelSCLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(createBtn1)
                .addGap(51, 51, 51)
                .addComponent(updateBtn1)
                .addGap(50, 50, 50)
                .addComponent(deleteBtn1)
                .addGap(42, 42, 42)
                .addComponent(clearBtn1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(exitBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        panelSCLayout.setVerticalGroup(
            panelSCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSCLayout.createSequentialGroup()
                .addGroup(panelSCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSCLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(69, 69, 69))
                    .addGroup(panelSCLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(showUsersBtn1)
                        .addGap(39, 39, 39)
                        .addGroup(panelSCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(sCComboSId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelSCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(sCComboCId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelSCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(sCComboSemId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 107, Short.MAX_VALUE)))
                .addGroup(panelSCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createBtn1)
                    .addComponent(updateBtn1)
                    .addComponent(deleteBtn1)
                    .addComponent(exitBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearBtn1))
                .addGap(23, 23, 23))
        );

        PanelLC.setBackground(new java.awt.Color(255, 204, 255));

        showUsersBtn2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        showUsersBtn2.setText("Show Lecturer Relation");
        showUsersBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showUsersBtn2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Lecturer ID");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Course ID");

        createBtn2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        createBtn2.setText("Create");
        createBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtn2ActionPerformed(evt);
            }
        });

        updateBtn2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        updateBtn2.setText("Update");
        updateBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtn2ActionPerformed(evt);
            }
        });

        deleteBtn2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deleteBtn2.setText("Delete");
        deleteBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtn2ActionPerformed(evt);
            }
        });

        clearBtn2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        clearBtn2.setText("Clear");
        clearBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtn2ActionPerformed(evt);
            }
        });

        exitBtn2.setBackground(new java.awt.Color(255, 102, 102));
        exitBtn2.setText("Exit");
        exitBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtn2ActionPerformed(evt);
            }
        });

        tableBD2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tableBD2);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Semester ID");

        javax.swing.GroupLayout PanelLCLayout = new javax.swing.GroupLayout(PanelLC);
        PanelLC.setLayout(PanelLCLayout);
        PanelLCLayout.setHorizontalGroup(
            PanelLCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLCLayout.createSequentialGroup()
                .addGroup(PanelLCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLCLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(showUsersBtn2))
                    .addGroup(PanelLCLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelLCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelLCLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lCComboSId, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelLCLayout.createSequentialGroup()
                                .addGroup(PanelLCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(PanelLCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lCComboLId, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lCComboCId, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(91, 91, 91)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(PanelLCLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(createBtn2)
                .addGap(51, 51, 51)
                .addComponent(updateBtn2)
                .addGap(50, 50, 50)
                .addComponent(deleteBtn2)
                .addGap(42, 42, 42)
                .addComponent(clearBtn2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(exitBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        PanelLCLayout.setVerticalGroup(
            PanelLCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLCLayout.createSequentialGroup()
                .addGroup(PanelLCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLCLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(showUsersBtn2)
                        .addGap(48, 48, 48)
                        .addGroup(PanelLCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lCComboLId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelLCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lCComboCId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelLCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(lCComboSId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 38, Short.MAX_VALUE))
                    .addGroup(PanelLCLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(69, 69, 69)
                .addGroup(PanelLCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createBtn2)
                    .addComponent(updateBtn2)
                    .addComponent(deleteBtn2)
                    .addComponent(exitBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearBtn2))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout panelCenterLayout = new javax.swing.GroupLayout(panelCenter);
        panelCenter.setLayout(panelCenterLayout);
        panelCenterLayout.setHorizontalGroup(
            panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSemester, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelSC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelLC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCenterLayout.setVerticalGroup(
            panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSemester, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelSC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelLC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(semesterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sCBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lCBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(semesterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sCBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lCBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panelCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lCBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lCBtnActionPerformed
        // TODO add your handling code here:
        PanelLC.setVisible(true);
        panelSemester.setVisible(false);
        panelSC.setVisible(false);
        
       emptyCombos();
       fillCombos();
    }//GEN-LAST:event_lCBtnActionPerformed

    private void semesterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semesterBtnActionPerformed
        // TODO add your handling code here:
        panelSemester.setVisible(true);
        PanelLC.setVisible(false);
        panelSC.setVisible(false);
        
        emptyCombos();
        fillCombos();
    }//GEN-LAST:event_semesterBtnActionPerformed

    private void sCBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sCBtnActionPerformed
        // TODO add your handling code here:
        panelSC.setVisible(true);
        panelSemester.setVisible(false);
        PanelLC.setVisible(false);
        
       emptyCombos();
       fillCombos();
        
    }//GEN-LAST:event_sCBtnActionPerformed

        private void emptyCombos(){
            sCComboSId.removeAllItems();
            sCComboCId.removeAllItems();
            sCComboSemId.removeAllItems();
            lCComboLId.removeAllItems();
            lCComboCId.removeAllItems();
            lCComboSId.removeAllItems();

            
        }
        
    
        private void fillCombos(){
        try {
           String sqlLId = "SELECT LecturerId from vgccollege.Lecturer";
           String sqlCId = "SELECT CourseId from vgccollege.Course";
           String sqlSemId = "SELECT SemesterId from vgccollege.semester";
           String sqlStId = "SELECT StudentId from vgccollege.Student"; 
            
            Connection conn = MySQLConnection.getConnection();
            
            PreparedStatement pstSt = conn.prepareStatement(sqlStId);
            ResultSet rsSt = pstSt.executeQuery();
            
            PreparedStatement pstLec = conn.prepareStatement(sqlLId);
            ResultSet rsLec = pstLec.executeQuery();
            
            PreparedStatement pstC = conn.prepareStatement(sqlCId);
            ResultSet rsC = pstC.executeQuery();
            
            PreparedStatement pstS = conn.prepareStatement(sqlSemId);
            ResultSet rsSemId = pstS.executeQuery();
            
            while (rsSt.next()){
                String StCombo = rsSt.getString("StudentId");
                sCComboSId.addItem(StCombo); 
                
            }
            
            while (rsLec.next()){
                String LectCombo = rsLec.getString("LecturerId");
                lCComboLId.addItem(LectCombo);               
            }
            
            while (rsC.next()){
                String courseCombo = rsC.getString("CourseId");
                lCComboCId.addItem(courseCombo);               
            }
            
            while (rsSemId.next()){
                String SemCombo = rsSemId.getString("SemesterId");
                lCComboSId.addItem(SemCombo);               
            }
            ;
            sCComboSId.setSelectedIndex(0);
            lCComboLId.setSelectedIndex(-1);
            lCComboCId.setSelectedIndex(-1);
            lCComboSId.setSelectedIndex(-1);
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    
    
    private void showUsersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showUsersBtnActionPerformed
        // TODO add your handling code here:

        try (Connection conn = MySQLConnection.getConnection()){

            String sql = "SELECT * FROM vgccollege.Semester";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            tableBD.setModel(DbUtils.resultSetToTableModel(rs));

        }catch (Exception exception) {

            JOptionPane.showMessageDialog(null, exception);
            exception.printStackTrace();

    }//GEN-LAST:event_showUsersBtnActionPerformed
    }    
        
    private void findBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findBtnActionPerformed
        // TODO add your handling code here:

        String SemIDStr = semesterIdField.getText();

        try (Connection conn = MySQLConnection.getConnection()){

            String sql = "SELECT * FROM vgccollege.Semester" + " WHERE SemesterId = '" + SemIDStr + "'";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.executeQuery();
            ResultSet rs = pst.executeQuery();

            if(rs.next()){
                descriptionField.setText(rs.getString("sDescription"));

            } else {
                JOptionPane.showMessageDialog(null, "Semester wasn't found");
            }

        }catch (Exception exception) {

            JOptionPane.showMessageDialog(null, exception);
            exception.printStackTrace();

        }

    }//GEN-LAST:event_findBtnActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:

        String SemIDStr = semesterIdField.getText();
        String descStr = descriptionField.getText();

        try (Connection conn = MySQLConnection.getConnection()){

            String mySQLQuery =
            "INSERT INTO vgccollege.Semester" + "(SemesterId, sDescription)"
            + "VALUES (?,?)";

            PreparedStatement pst = conn.prepareStatement(mySQLQuery);

            pst.setString(1, SemIDStr);
            pst.setString(2, descStr);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "New Semester created successfully");

        }catch (Exception exception) {

            JOptionPane.showMessageDialog(null, exception);
            exception.printStackTrace();

        }

    }//GEN-LAST:event_createBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:

        String SemIDStr = semesterIdField.getText();
        String descStr = descriptionField.getText();

        try (Connection conn = MySQLConnection.getConnection()){

            String mySQLQuery =
            "UPDATE vgccollege.Semester" + " SET sDescription=?  WHERE SemesterId=?";

            PreparedStatement pst = conn.prepareStatement(mySQLQuery);

            pst.setString(2, SemIDStr);
            pst.setString(1, descStr);

            int i = pst.executeUpdate();
            pst.executeUpdate();

            if(i>0){
                JOptionPane.showMessageDialog(null, "semester updated successful");
            } else {
                JOptionPane.showMessageDialog(null, "semester could not be made");
            }

        }catch (Exception exception) {

            JOptionPane.showMessageDialog(null, exception);
            exception.printStackTrace();

        }

    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:

        int confirmation = JOptionPane.showConfirmDialog(null, "Are your sure you want to delete the semester?","Warning", JOptionPane.YES_NO_OPTION);

        if (confirmation == 0)

        {

            try (Connection conn = MySQLConnection.getConnection()){

                String sqlDel =
                "DELETE FROM vgccollege.Semester" + " WHERE SemesterId =?";

                PreparedStatement pst = conn.prepareStatement(sqlDel);
                pst.setString(1, semesterIdField.getText());
                int i = pst.executeUpdate();
                pst.executeUpdate();

                if(i>0){
                    JOptionPane.showMessageDialog(null, "Semester deleted successfully");
                } else {
                    JOptionPane.showMessageDialog(null, "Semester not found");
                }

            }catch(Exception exception) {

                JOptionPane.showMessageDialog(null, exception);
                exception.printStackTrace();
            }
        } else {

            JOptionPane.showMessageDialog(null, "The semester wasn't deleted");
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        semesterIdField.setText("");
        descriptionField.setText("");
        SectionField.setText("");

    }//GEN-LAST:event_clearBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    private void showUsersBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showUsersBtn1ActionPerformed
        // TODO add your handling code here:
                try (Connection conn = MySQLConnection.getConnection()){

            String sql = "SELECT * FROM vgccollege.Semester";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            tableBD.setModel(DbUtils.resultSetToTableModel(rs));

        }catch (Exception exception) {

            JOptionPane.showMessageDialog(null, exception);
            exception.printStackTrace();
        }
    }//GEN-LAST:event_showUsersBtn1ActionPerformed

    private void createBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtn1ActionPerformed
        // TODO add your handling code here:
        String stIdSt = sCComboSId.getSelectedItem().toString();
        String cIdSt = sCComboCId.getSelectedItem().toString();
        String semtIdSt = sCComboSemId.getSelectedItem().toString();
        String empty = "";
        
        
        try (Connection conn = MySQLConnection.getConnection()){

            String mySQLQuery =
            "INSERT INTO vgccollege.StudentCourse" + "(StudentId, CourseId, SemesterId, concatValue)"
            + "VALUES (?,?,?,?)";

            PreparedStatement pst = conn.prepareStatement(mySQLQuery);

            pst.setString(1, stIdSt);
            pst.setString(2, cIdSt);
            pst.setString(3, semtIdSt);
            pst.setString(4, empty);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "New relation created successfully");

        }catch (Exception exception) {

            JOptionPane.showMessageDialog(null, exception);
            exception.printStackTrace();

        }
    }//GEN-LAST:event_createBtn1ActionPerformed

    private void updateBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateBtn1ActionPerformed

    private void deleteBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBtn1ActionPerformed

    private void clearBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearBtn1ActionPerformed

    private void exitBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtn1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitBtn1ActionPerformed

    private void showUsersBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showUsersBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showUsersBtn2ActionPerformed

    private void createBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createBtn2ActionPerformed

    private void updateBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateBtn2ActionPerformed

    private void deleteBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBtn2ActionPerformed

    private void clearBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearBtn2ActionPerformed

    private void exitBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtn2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitBtn2ActionPerformed

    private void sCComboSIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sCComboSIdActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_sCComboSIdActionPerformed

    private void sCComboCIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sCComboCIdItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_sCComboCIdItemStateChanged

    private void sCComboSIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sCComboSIdItemStateChanged
        // TODO add your handling code here:
                
                sCComboCId.removeAllItems();
                sCComboSemId.removeAllItems();
                String studentId = sCComboSId.getSelectedItem().toString();
        
        try {
            String sqlCId ="SELECT CourseId from vgccollege.Course WHERE DegreeId = (SELECT degreeId FROM vgccollege.Student where StudentId = ?)";
            String sqlSemId ="SELECT SemesterId from vgccollege.semester";
            
            
            Connection conn = MySQLConnection.getConnection();
            PreparedStatement pstSId = conn.prepareStatement(sqlCId);
            pstSId.setString(1, studentId);
            ResultSet rsSId = pstSId.executeQuery();
            
            PreparedStatement pstB = conn.prepareStatement(sqlSemId);
            ResultSet rsSemId = pstB.executeQuery();
            
            while (rsSId.next()){
                String courseCombo = rsSId.getString("CourseId");
                sCComboCId.addItem(courseCombo); 
                
            }
            
            while (rsSemId.next()){
                String SemCombo = rsSemId.getString("SemesterId");
                sCComboSemId.addItem(SemCombo);               
            }
            
            sCComboCId.setSelectedIndex(-1);
            sCComboSemId.setSelectedIndex(-1);
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_sCComboSIdItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcademicMDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcademicMDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcademicMDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcademicMDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcademicMDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelLC;
    private javax.swing.JTextField SectionField;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton clearBtn1;
    private javax.swing.JButton clearBtn2;
    private javax.swing.JButton createBtn;
    private javax.swing.JButton createBtn1;
    private javax.swing.JButton createBtn2;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton deleteBtn1;
    private javax.swing.JButton deleteBtn2;
    private javax.swing.JTextField descriptionField;
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton exitBtn1;
    private javax.swing.JButton exitBtn2;
    private javax.swing.JButton findBtn;
    private javax.swing.JLabel fullNameW;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton lCBtn;
    private javax.swing.JComboBox lCComboCId;
    private javax.swing.JComboBox lCComboLId;
    private javax.swing.JComboBox lCComboSId;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelSC;
    private javax.swing.JPanel panelSemester;
    private javax.swing.JButton sCBtn;
    private javax.swing.JComboBox sCComboCId;
    private javax.swing.JComboBox sCComboSId;
    private javax.swing.JComboBox sCComboSemId;
    private javax.swing.JButton semesterBtn;
    public javax.swing.JTextField semesterIdField;
    private javax.swing.JButton showUsersBtn;
    private javax.swing.JButton showUsersBtn1;
    private javax.swing.JButton showUsersBtn2;
    private javax.swing.JTable tableBD;
    private javax.swing.JTable tableBD2;
    private javax.swing.JTable tableSC;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton updateBtn1;
    private javax.swing.JButton updateBtn2;
    // End of variables declaration//GEN-END:variables
}
