/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage.pk;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author feran
 */
public class AdmDashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public AdmDashboard() {
        initComponents();
        scaleImage();
        
        fullNameW.setText(LoginSesion.fullUserName);
        
    }
    
    public void scaleImage(){
        ImageIcon icon = new ImageIcon(getClass().getResource("/newpackage/pk/images/manageUsers.png"));
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(manageUserImage.getWidth(), manageUserImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaleIcon = new ImageIcon(imgScale);
        manageUserImage.setIcon(scaleIcon);
        
        ImageIcon icon2 = new ImageIcon(getClass().getResource("/newpackage/pk/images/branches.png"));
        Image img2 = icon2.getImage();
        Image imgScale2 = img2.getScaledInstance(manageBranchImage.getWidth(), manageBranchImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaleIcon2 = new ImageIcon(imgScale2);
        manageBranchImage.setIcon(scaleIcon2);
        
        
        ImageIcon icon3 = new ImageIcon(getClass().getResource("/newpackage/pk/images/degrees.png"));
        Image img3 = icon3.getImage();
        Image imgScale3 = img3.getScaledInstance(manageDegreeImage.getWidth(), manageDegreeImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaleIcon3 = new ImageIcon(imgScale3);
        manageDegreeImage.setIcon(scaleIcon3);
        
        
        ImageIcon icon4 = new ImageIcon(getClass().getResource("/newpackage/pk/images/courses.png"));
        Image img4 = icon4.getImage();
        Image imgScale4 = img4.getScaledInstance(manageCourseImage.getWidth(), manageCourseImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaleIcon4 = new ImageIcon(imgScale4);
        manageCourseImage.setIcon(scaleIcon4);
        
        ImageIcon icon5 = new ImageIcon(getClass().getResource("/newpackage/pk/images/academicM.png"));
        Image img5 = icon5.getImage();
        Image imgScale5 = img5.getScaledInstance(manageCourseImage.getWidth(), manageCourseImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaleIcon5 = new ImageIcon(imgScale5);
        manageAcademicImage.setIcon(scaleIcon5); 
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fullNameW = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        MUsersButton = new javax.swing.JButton();
        manageUserImage = new javax.swing.JLabel();
        MBranchesButton = new javax.swing.JButton();
        manageBranchImage = new javax.swing.JLabel();
        manageDegreeImage = new javax.swing.JLabel();
        MCoursesButton = new javax.swing.JButton();
        manageCourseImage = new javax.swing.JLabel();
        MDegreesButton = new javax.swing.JButton();
        MAcademicButton = new javax.swing.JButton();
        manageAcademicImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(220, 122, 55));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Welcome!");

        fullNameW.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        fullNameW.setText("jLabel2");

        backButton.setText("<-  Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fullNameW, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 477, Short.MAX_VALUE)
                .addComponent(backButton)
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(backButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fullNameW, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addContainerGap())
        );

        MUsersButton.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        MUsersButton.setText("Manage Users");
        MUsersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MUsersButtonActionPerformed(evt);
            }
        });

        MBranchesButton.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        MBranchesButton.setText("Manage Branches");
        MBranchesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MBranchesButtonActionPerformed(evt);
            }
        });

        MCoursesButton.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        MCoursesButton.setText("Manage Courses");
        MCoursesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MCoursesButtonActionPerformed(evt);
            }
        });

        MDegreesButton.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        MDegreesButton.setText("Manage Degrees");
        MDegreesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MDegreesButtonActionPerformed(evt);
            }
        });

        MAcademicButton.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        MAcademicButton.setText("Academic management");
        MAcademicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAcademicButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(manageAcademicImage, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(MAcademicButton, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(manageCourseImage, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(MCoursesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(manageDegreeImage, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(MDegreesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(manageBranchImage, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(MBranchesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(manageUserImage, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(MUsersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(MUsersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(manageUserImage, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(MBranchesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(manageBranchImage, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(MDegreesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(manageDegreeImage, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(MCoursesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(manageCourseImage, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(MAcademicButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(manageAcademicImage, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        new LoginForm().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    private void MUsersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MUsersButtonActionPerformed
        // TODO add your handling code here:
        
        new ManageUsers().setVisible(true);
    }//GEN-LAST:event_MUsersButtonActionPerformed

    private void MBranchesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MBranchesButtonActionPerformed
        // TODO add your handling code here:
        new ManageBranches().setVisible(true);
    }//GEN-LAST:event_MBranchesButtonActionPerformed

    private void MDegreesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MDegreesButtonActionPerformed
        // TODO add your handling code here:
        new ManageDegrees().setVisible(true);
    }//GEN-LAST:event_MDegreesButtonActionPerformed

    private void MCoursesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCoursesButtonActionPerformed
        // TODO add your handling code here:
        new ManageCourses().setVisible(true);
    }//GEN-LAST:event_MCoursesButtonActionPerformed

    private void MAcademicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAcademicButtonActionPerformed
        // TODO add your handling code here:
        new AcademicMDashboard().setVisible(true);
    }//GEN-LAST:event_MAcademicButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdmDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdmDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdmDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdmDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdmDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MAcademicButton;
    private javax.swing.JButton MBranchesButton;
    private javax.swing.JButton MCoursesButton;
    private javax.swing.JButton MDegreesButton;
    private javax.swing.JButton MUsersButton;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel fullNameW;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel manageAcademicImage;
    private javax.swing.JLabel manageBranchImage;
    private javax.swing.JLabel manageCourseImage;
    private javax.swing.JLabel manageDegreeImage;
    private javax.swing.JLabel manageUserImage;
    // End of variables declaration//GEN-END:variables
}
